// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: chaton.proto

package chaton

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	// Open the connection with the server (subscribe to recieve message from him)
	// The message content should be the nick name of the client (can be optional)
	MsgType_CONNECT MsgType = 0
	// Set the client nickname
	// The message content should be the nick name of the client
	MsgType_SET_NICKNAME MsgType = 1
	// Send a message, the message content is what is send to other clients
	MsgType_MESSAGE MsgType = 2
	// Leave the server
	// The message content is what the user say before leaving (can be optional)
	MsgType_QUIT MsgType = 3
	// Send action message
	// The message content represent what the user do
	MsgType_ME MsgType = 4
	// List users connected on the server
	// The message is ignored by the server
	MsgType_LIST MsgType = 5
	MsgType_TO   MsgType = 6 // Send message only visible by mentioned users
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "CONNECT",
		1: "SET_NICKNAME",
		2: "MESSAGE",
		3: "QUIT",
		4: "ME",
		5: "LIST",
		6: "TO",
	}
	MsgType_value = map[string]int32{
		"CONNECT":      0,
		"SET_NICKNAME": 1,
		"MESSAGE":      2,
		"QUIT":         3,
		"ME":           4,
		"LIST":         5,
		"TO":           6,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_chaton_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_chaton_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_chaton_proto_rawDescGZIP(), []int{0}
}

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Author  string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"` // Ignored by the server when recieving from clients
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chaton_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_chaton_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_chaton_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Msg) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MsgType `protobuf:"varint,1,opt,name=type,proto3,enum=chaton.MsgType" json:"type,omitempty"`
	Msg  *Msg    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chaton_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_chaton_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_chaton_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_CONNECT
}

func (x *Event) GetMsg() *Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

var File_chaton_proto protoreflect.FileDescriptor

var file_chaton_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x68, 0x61, 0x74, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x63, 0x68, 0x61, 0x74, 0x6f, 0x6e, 0x22, 0x37, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22,
	0x4b, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6f, 0x6e, 0x2e,
	0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x6f, 0x6e, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0x59, 0x0a, 0x07,
	0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4e, 0x4e, 0x45,
	0x43, 0x54, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x54, 0x5f, 0x4e, 0x49, 0x43, 0x4b,
	0x4e, 0x41, 0x4d, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47,
	0x45, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x51, 0x55, 0x49, 0x54, 0x10, 0x03, 0x12, 0x06, 0x0a,
	0x02, 0x4d, 0x45, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x05, 0x12,
	0x06, 0x0a, 0x02, 0x54, 0x4f, 0x10, 0x06, 0x32, 0x34, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x74, 0x6f,
	0x6e, 0x12, 0x2a, 0x0a, 0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x0d, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x6f, 0x6e, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x0d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6f,
	0x6e, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_chaton_proto_rawDescOnce sync.Once
	file_chaton_proto_rawDescData = file_chaton_proto_rawDesc
)

func file_chaton_proto_rawDescGZIP() []byte {
	file_chaton_proto_rawDescOnce.Do(func() {
		file_chaton_proto_rawDescData = protoimpl.X.CompressGZIP(file_chaton_proto_rawDescData)
	})
	return file_chaton_proto_rawDescData
}

var file_chaton_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chaton_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chaton_proto_goTypes = []interface{}{
	(MsgType)(0),  // 0: chaton.MsgType
	(*Msg)(nil),   // 1: chaton.Msg
	(*Event)(nil), // 2: chaton.Event
}
var file_chaton_proto_depIdxs = []int32{
	0, // 0: chaton.Event.type:type_name -> chaton.MsgType
	1, // 1: chaton.Event.msg:type_name -> chaton.Msg
	2, // 2: chaton.Chaton.Join:input_type -> chaton.Event
	2, // 3: chaton.Chaton.Join:output_type -> chaton.Event
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chaton_proto_init() }
func file_chaton_proto_init() {
	if File_chaton_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chaton_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chaton_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chaton_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chaton_proto_goTypes,
		DependencyIndexes: file_chaton_proto_depIdxs,
		EnumInfos:         file_chaton_proto_enumTypes,
		MessageInfos:      file_chaton_proto_msgTypes,
	}.Build()
	File_chaton_proto = out.File
	file_chaton_proto_rawDesc = nil
	file_chaton_proto_goTypes = nil
	file_chaton_proto_depIdxs = nil
}
